#!/usr/bin/env node

//those are the files that we use for the setup of the database
var sql_commands = ['bodega.sql', 'core.plsql', 'search_en.plsql', 'defaultdata.sql', 'actionconf.plsql', 'rankings.sql', 'purchasing.plsql', 'payments_stripe.sql'];

//those are the migration files which we will use in order to migrate and update successfully the db
var update_sql_commands = [];

var exec = require('child_process').exec;

var run = function(command, fn) {
    var output = '';
    exec(command, function (error, stdout, stderr) {
        output += stdout;
        output += stderr;
        if (error !== null) {
            output += error;
        }
        if (fn !== undefined) {
            fn(output.trim());
        }
    });
}

function series(command_list) {
    //this is out command for the sql files
    var sql_command = function(fileName) {
        var command = 'psql -d ' + config.database.name + ' -U ' + config.database.user + ' -f ';
        command += npm_path + '/../sql/' + fileName + ' 1>/dev/null';
        return command;
    }

    function next() {
        var element = command_list.shift();
        if (command_list.length > 0) {
            var command = '';
            //the element is a sql file so make it a full command
            if (element.indexOf('.sql') > -1 || element.indexOf('.plsql') > -1) {
                command = sql_command(element);
            } else {
                //its already a command
                command = element;
            }
            run(command, function(result) {
                 console.log(result.trim());
                 next();
            });
        } else {
            console.log('====End!!!====');
        }
    }
    next();
}

var npm_path = '';
var config = {};
// find the npm dir, the npm dir is
// dir where the package.json file is
//and parse the package.json
run('npm prefix', function(npmPath) {
    var fs = require('fs');
    npm_path = npmPath;
    config = JSON.parse(fs.readFileSync((npm_path + '/config.json'), 'utf8'));

    var argument = process.argv[2];

    if (argument == 'update') {
        console.log('====Updating the database schema!!====');
        series(update_sql_commands);
    } else if (argument == 'setup') {
        console.log('====Creating the database schema!!====');
        sql_commands.unshift('createdb -O ' + config.database.name + ' ' + config.database.name);
        sql_commands.unshift('dropdb ' + config.database.user);
        series(sql_commands);
    } else {
        console.log('This script needs an argument, this can be either update or setup.');
        console.log('setup: creates the database');
        console.log('update: migrates the database');
        return;
    }
});

